# Generated by Django 2.1 on 2018-08-19 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='idade',
        ),
    ]
